<footer>
<h3>CTRL-ALT-INNOVATE: Where Disruption Meets Purpose.</h3>
<a class="logo-icon" href="index.php"><img src="images/logo.png" alt="CTRL-ALT-INNOVATE Logo"></a>
<div class="footer-links">
    <!-- Links open in new page
    https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target-->
    <a href="https://trisdinning.atlassian.net/jira/software/projects/MOR/summary" target="_blank">Jira</a>
    <a href="https://github.com/Dynamicarian/CTRL-ALT-INNOVATE" target="_blank">Github</a>
    <a href="login.php" class="manager_page_button">Manager View</a>
    <p>&#169; CTRL-ALT-DELETE</p>
</div>
</footer>