<header>
    <nav>
        <a class="logo-icon" href="index.php"><img src="images/logo.png" alt="CTRL-ALT-INNOVATE Logo"></a>
        <div class="nav-options">
            <a href="index.php">Home</a>
            <a href="jobs.php">Jobs</a>
            <a href="apply.php">Apply</a>
            <a href="about.php">About</a>
            <!-- Contact Us link with email link -->
            <a href="mailto:test@test.com">Contact Us!</a>
        </div>
    </nav>
</header>